site_name: educast.nrw App Dokumentation
site_author: 'Sebastian Hohn, Lennart Ferlings, Bennit Strack, Hannah Niehaus, Tom Sch√ºppler'

nav:
  - Home: index.md
  - Setup: setup.md
  - Userguide: userguide.md
  - Struktur: struktur.md
  - Datenbank: database.md
  - Login: login.md
  - Aufbau/Entwurf: entwurf.md
  - Implementation: 
    - Download: implementation/download.md
    - Player: implementation/player.md
  - Restriktionen: restriktionen.md
  - Ausblick: future_work.md


theme:
  name: material
  language: de
  logo: assets/images/icon_RGB.png
  favicon: assets/images/favicon.ico